import {
  BANK_OPTIONS,
  buildAfterSalesResolutionPayload,
  buildAppealResolutionPayload,
  buildEligibilityReviewPayload,
  buildResolutionPayload,
  buildReviewAppealPayload,
  buildReviewApplicationPayload,
  getMenuItemFieldId,
  getMerchantFieldClassName,
  getMerchantFieldId,
} from '@/features/delivery-console'
import {
  acceptOrder,
  approveMerchantApplication,
  assignRider,
  deliverOrder,
  pickupOrder,
  readyOrder,
  rejectMerchantApplication,
  removeStoreMenuItem,
  resolveAfterSalesTicket,
  resolveEligibilityReview,
  resolveReviewAppeal,
  resolveTicket,
  submitEligibilityReview,
  submitReviewAppeal,
  updateRiderProfile,
  withdrawRiderIncome,
} from '@/api'

export function buildCustomerProps({
  pageView,
  pageState,
  sessionService,
  customerService,
  navigate,
}: any) {
  return {
    activeReviewOrder: pageView.activeReviewOrder,
    activeCustomerOrder: pageView.activeCustomerOrder,
    afterSalesDrafts: pageState.afterSalesDrafts,
    afterSalesErrors: pageState.afterSalesErrors,
    addCustomerAddress: customerService.addCustomerAddress,
    addressDraft: pageState.addressDraft,
    addressFormErrors: pageState.addressFormErrors,
    canReviewOrder: pageView.canReviewOrder,
    cartSubtotal: pageView.cartSubtotal,
    cartTotal: pageView.cartTotal,
    availableCheckoutCoupons: pageView.availableCheckoutCoupons,
    categoryStores: pageView.categoryStores,
    couponDiscountCents: pageView.couponDiscountCents,
    chooseStoreCategory: pageView.chooseStoreCategory,
    completedCustomerOrders: pageView.completedCustomerOrders,
    customerStoreSearch: pageState.customerStoreSearch,
    customerStoreSearchDraft: pageState.customerStoreSearchDraft,
    customerStoreSearchHistory: sessionService.customerStoreSearchHistory,
    customRechargeAmount: pageState.customRechargeAmount,
    customerNameDraft: pageState.customerNameDraft,
    customerOrders: pageView.customerOrders,
    customerWorkspaceView: pageView.customerWorkspaceView,
    DELIVERY_FEE_CENTS: pageView.DELIVERY_FEE_CENTS,
    deliveryAddress: pageState.deliveryAddress,
    deliveryAddressError: pageState.deliveryAddressError,
    enterStore: pageView.enterStore,
    formatAggregateRating: pageView.formatAggregateRating,
    formatBusinessHours: pageView.formatBusinessHours,
    formatPrice: pageView.formatPrice,
    formatStoreAvailability: pageView.formatStoreAvailability,
    formatStoreStatus: pageView.formatStoreStatus,
    formatTime: pageView.formatTime,
    getCategoryMeta: pageView.getCategoryMeta,
    getRemainingReviewDays: pageView.getRemainingReviewDays,
    getRemainingRefundableQuantity: customerService.getRemainingRefundableQuantity,
    hasPendingRiderReview: pageView.hasPendingRiderReview,
    hasPendingStoreReview: pageView.hasPendingStoreReview,
    isStoreCurrentlyOpen: pageView.isStoreCurrentlyOpen,
    isCheckoutExpanded: pageState.isCheckoutExpanded,
    leaveStore: pageView.leaveStore,
    navigate,
    openCheckout: pageView.openCheckout,
    openRechargePage: customerService.openRechargePage,
    orderChatDrafts: pageState.orderChatDrafts,
    orderChatErrors: pageState.orderChatErrors,
    partialRefundDrafts: pageState.partialRefundDrafts,
    partialRefundErrors: pageState.partialRefundErrors,
    payableTotalCents: pageView.payableTotalCents,
    parsedRechargeAmount: pageView.parsedRechargeAmount,
    pendingCustomerReviewOrders: pageView.pendingCustomerReviewOrders,
    quantities: pageState.quantities,
    rechargeAmountError: pageView.rechargeAmountError,
    rechargeAmountPreview: pageView.rechargeAmountPreview,
    RECHARGE_PRESET_AMOUNTS: pageView.RECHARGE_PRESET_AMOUNTS,
    remainingBalanceAfterCheckout: pageView.remainingBalanceAfterCheckout,
    removeCustomerAddress: customerService.removeCustomerAddress,
    setDefaultCustomerAddress: customerService.setDefaultCustomerAddress,
    remark: pageState.remark,
    scheduledDeliveryTime: pageState.scheduledDeliveryTime,
    resetStoreCategory: pageView.resetStoreCategory,
    REVIEW_WINDOW_DAYS: pageView.REVIEW_WINDOW_DAYS,
    reviewDrafts: pageState.reviewDrafts,
    reviewErrors: pageState.reviewErrors,
    RIDER_REVIEW_REASON_OPTIONS: pageView.RIDER_REVIEW_REASON_OPTIONS,
    saveCustomerName: customerService.saveCustomerName,
    selectedCustomer: pageView.selectedCustomer,
    selectedCoupon: pageView.selectedCoupon,
    selectedCouponId: pageState.selectedCouponId,
    selectedRechargeAmount: pageState.selectedRechargeAmount,
    scheduledDeliveryError: pageState.scheduledDeliveryError,
    selectedStore: pageView.selectedStore,
    selectedStoreCategory: pageState.selectedStoreCategory,
    selectedStoreCanOrder: pageView.selectedStoreCanOrder,
    selectedStoreHasMenu: pageView.selectedStoreHasMenu,
    selectRechargeAmount: customerService.selectRechargeAmount,
    setAddressDraft: pageState.setAddressDraft,
    setAddressFormErrors: pageState.setAddressFormErrors,
    setAfterSalesDrafts: pageState.setAfterSalesDrafts,
    setAfterSalesErrors: pageState.setAfterSalesErrors,
    setCustomRechargeAmount: pageState.setCustomRechargeAmount,
    setCustomerNameDraft: pageState.setCustomerNameDraft,
    setCustomerStoreSearch: pageState.setCustomerStoreSearch,
    setCustomerStoreSearchDraft: pageState.setCustomerStoreSearchDraft,
    setDeliveryAddress: pageState.setDeliveryAddress,
    setDeliveryAddressError: pageState.setDeliveryAddressError,
    setError: sessionService.setError,
    setIsCheckoutExpanded: pageState.setIsCheckoutExpanded,
    setOrderChatDrafts: pageState.setOrderChatDrafts,
    setOrderChatErrors: pageState.setOrderChatErrors,
    setPartialRefundDrafts: pageState.setPartialRefundDrafts,
    setPartialRefundErrors: pageState.setPartialRefundErrors,
    setRemark: pageState.setRemark,
    setReviewDrafts: pageState.setReviewDrafts,
    setReviewErrors: pageState.setReviewErrors,
    setScheduledDeliveryError: pageState.setScheduledDeliveryError,
    setScheduledDeliveryTime: pageState.setScheduledDeliveryTime,
    setScheduledDeliveryTouched: pageState.setScheduledDeliveryTouched,
    setSelectedCouponId: pageState.setSelectedCouponId,
    setSelectedRechargeAmount: pageState.setSelectedRechargeAmount,
    statusLabels: pageView.statusLabels,
    STORE_REVIEW_REASON_OPTIONS: pageView.STORE_REVIEW_REASON_OPTIONS,
    storeCategories: pageView.storeCategories,
    suggestedDeliveryTime: pageView.todayDeliveryWindow.minimumValue,
    clearCustomerStoreSearchHistory: customerService.clearCustomerStoreSearchHistory,
    removeCustomerStoreSearchHistoryItem: customerService.removeCustomerStoreSearchHistoryItem,
    stateTickets: sessionService.state?.tickets ?? [],
    submitAfterSalesRequest: customerService.submitAfterSalesRequest,
    submitCustomerStoreSearch: customerService.submitCustomerStoreSearch,
    submitOrder: customerService.submitOrder,
    submitOrderChatMessage: customerService.submitOrderChatMessage,
    submitPartialRefundRequest: customerService.submitPartialRefundRequest,
    submitRechargeFromPage: customerService.submitRechargeFromPage,
    submitReview: customerService.submitReview,
    todayDeliveryCutoff: pageView.todayDeliveryWindow.cutoffValue,
    canSubmitPartialRefund: customerService.canSubmitPartialRefund,
    updateQuantity: pageView.updateQuantity,
    updateReviewDraft: pageView.updateReviewDraft,
    visibleStores: pageView.visibleStores,
  }
}

export function buildMerchantProps({
  pageView,
  pageState,
  sessionService,
  customerService,
  merchantService,
  navigate,
}: any) {
  return {
    BANK_OPTIONS,
    buildEligibilityReviewPayload,
    buildReviewAppealPayload,
    currentDisplayName: pageView.currentDisplayName,
    eligibilityReviewDrafts: pageState.eligibilityReviewDrafts,
    enterMerchantStore: pageView.enterMerchantStore,
    formatAggregateRating: pageView.formatAggregateRating,
    formatBusinessHours: pageView.formatBusinessHours,
    formatPrice: pageView.formatPrice,
    formatTime: pageView.formatTime,
    getMenuItemDraft: merchantService.getMenuItemDraft,
    getMenuItemFieldId,
    getMerchantFieldClassName,
    getMerchantFieldId,
    isMenuComposerExpanded: merchantService.isMenuComposerExpanded,
    isMenuItemImageUploading: merchantService.isMenuItemImageUploading,
    isMerchantImageUploading: pageState.isMerchantImageUploading,
    leaveMerchantStore: pageView.leaveMerchantStore,
    menuItemFormErrors: pageState.menuItemFormErrors,
    merchantAppealDrafts: pageState.merchantAppealDrafts,
    merchantApplicationView: pageView.merchantApplicationView,
    merchantDraft: pageState.merchantDraft,
    merchantFormErrors: pageState.merchantFormErrors,
    merchantPendingApplications: pageView.merchantPendingApplications,
    merchantProfile: pageView.merchantProfile,
    merchantProfileDraft: pageState.merchantProfileDraft,
    merchantProfileFormErrors: pageState.merchantProfileFormErrors,
    merchantReviewedApplications: pageView.merchantReviewedApplications,
    merchantStores: pageView.merchantStores,
    merchantWithdrawAmount: pageState.merchantWithdrawAmount,
    merchantWithdrawError: pageView.merchantWithdrawError,
    merchantWorkspaceView: pageView.merchantWorkspaceView,
    navigate,
    orderChatDrafts: pageState.orderChatDrafts,
    orderChatErrors: pageState.orderChatErrors,
    partialRefundResolutionDrafts: pageState.partialRefundResolutionDrafts,
    resolvePartialRefundRequest: merchantService.resolvePartialRefundRequest,
    role: pageView.role,
    runAction: sessionService.runAction,
    saveMerchantProfile: merchantService.saveMerchantProfile,
    selectedMerchantStoreId: pageState.selectedMerchantStoreId,
    setEligibilityReviewDrafts: pageState.setEligibilityReviewDrafts,
    setMenuComposerOpen: pageState.setMenuComposerOpen,
    setMenuItemDrafts: pageState.setMenuItemDrafts,
    setMenuItemFormErrors: pageState.setMenuItemFormErrors,
    setMerchantAppealDrafts: pageState.setMerchantAppealDrafts,
    setMerchantApplicationViewState: pageView.setMerchantApplicationViewState,
    setMerchantDraft: pageState.setMerchantDraft,
    setMerchantFormErrors: pageState.setMerchantFormErrors,
    setMerchantProfileDraft: pageState.setMerchantProfileDraft,
    setMerchantProfileFormErrors: pageState.setMerchantProfileFormErrors,
    setMerchantWithdrawAmount: pageState.setMerchantWithdrawAmount,
    setMerchantWithdrawFieldError: pageState.setMerchantWithdrawFieldError,
    setMerchantWorkspaceViewState: pageView.setMerchantWorkspaceViewState,
    setOrderChatDrafts: pageState.setOrderChatDrafts,
    setOrderChatErrors: pageState.setOrderChatErrors,
    setPartialRefundResolutionDrafts: pageState.setPartialRefundResolutionDrafts,
    state: sessionService.state,
    statusLabels: pageView.statusLabels,
    STORE_CATEGORIES: pageView.STORE_CATEGORIES,
    submitEligibilityReview,
    submitMerchantApplication: merchantService.submitMerchantApplication,
    submitOrderChatMessage: customerService.submitOrderChatMessage,
    removeStoreMenuItem,
    acceptOrder,
    readyOrder,
    submitReviewAppeal,
    submitStoreMenuItem: merchantService.submitStoreMenuItem,
    uploadMerchantImage: merchantService.uploadMerchantImage,
    uploadStoreMenuImage: merchantService.uploadStoreMenuImage,
    withdrawMerchantIncome: merchantService.withdrawMerchantIncome,
  }
}

export function buildRiderProps({
  pageView,
  pageState,
  sessionService,
  customerService,
}: any) {
  return {
    BANK_OPTIONS,
    buildEligibilityReviewPayload,
    buildReviewAppealPayload,
    currentDisplayName: pageView.currentDisplayName,
    eligibilityReviewDrafts: pageState.eligibilityReviewDrafts,
    formatAggregateRating: pageView.formatAggregateRating,
    formatPrice: pageView.formatPrice,
    formatTime: pageView.formatTime,
    orderChatDrafts: pageState.orderChatDrafts,
    orderChatErrors: pageState.orderChatErrors,
    riderAppealDrafts: pageState.riderAppealDrafts,
    riderOrders: pageView.riderOrders,
    role: pageView.role,
    runAction: sessionService.runAction,
    selectedRider: pageView.selectedRider,
    selectedRiderId: pageState.selectedRiderId,
    session: sessionService.session,
    setEligibilityReviewDrafts: pageState.setEligibilityReviewDrafts,
    setOrderChatDrafts: pageState.setOrderChatDrafts,
    setOrderChatErrors: pageState.setOrderChatErrors,
    setRiderAppealDrafts: pageState.setRiderAppealDrafts,
    setSelectedRiderId: pageState.setSelectedRiderId,
    state: sessionService.state,
    statusLabels: pageView.statusLabels,
    submitOrderChatMessage: customerService.submitOrderChatMessage,
    updateRiderProfile,
    withdrawRiderIncome,
    submitEligibilityReview,
    assignRider,
    pickupOrder,
    deliverOrder,
    submitReviewAppeal,
  }
}

export function buildAdminProps({ pageView, pageState, sessionService }: any) {
  return {
    afterSalesResolutionDrafts: pageState.afterSalesResolutionDrafts,
    afterSalesTickets: pageView.afterSalesTickets,
    appealResolutionDrafts: pageState.appealResolutionDrafts,
    applicationReviewDrafts: pageState.applicationReviewDrafts,
    buildAfterSalesResolutionPayload,
    buildAppealResolutionPayload,
    buildResolutionPayload,
    buildReviewApplicationPayload,
    eligibilityResolutionDrafts: pageState.eligibilityResolutionDrafts,
    formatTime: pageView.formatTime,
    pendingAppeals: pageView.pendingAppeals,
    pendingApplications: pageView.pendingApplications,
    pendingEligibilityReviews: pageView.pendingEligibilityReviews,
    resolutionDrafts: pageState.resolutionDrafts,
    runAction: sessionService.runAction,
    setAfterSalesResolutionDrafts: pageState.setAfterSalesResolutionDrafts,
    setAppealResolutionDrafts: pageState.setAppealResolutionDrafts,
    setApplicationReviewDrafts: pageState.setApplicationReviewDrafts,
    setEligibilityResolutionDrafts: pageState.setEligibilityResolutionDrafts,
    setResolutionDrafts: pageState.setResolutionDrafts,
    state: sessionService.state,
    approveMerchantApplication,
    rejectMerchantApplication,
    resolveReviewAppeal,
    resolveEligibilityReview,
    resolveAfterSalesTicket,
    resolveTicket,
  }
}
