import { ACCOUNT_STATUS, AFTER_SALES_REQUEST_TYPE, AFTER_SALES_RESOLUTION_MODE, APPEAL_ROLE, APPEAL_STATUS, APPLICATION_STATUS, ELIGIBILITY_REVIEW_TARGET, MEMBERSHIP_TIER, NOTE_STATUS, ORDER_STATUS, PARTIAL_REFUND_STATUS, PAYOUT_ACCOUNT_TYPE, REVIEW_STATUS, RIDER_AVAILABILITY, ROLE, STORE_CATEGORY, STORE_STATUS, TICKET_KIND, TICKET_STATUS } from '@/objects/core/SharedObjects'
import { decodeEnum } from '@/system/api/DecoderSupport'

export const decodeRole = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(ROLE))
export const decodeAccountStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(ACCOUNT_STATUS))
export const decodeMembershipTier = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(MEMBERSHIP_TIER))
export const decodeStoreCategory = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(STORE_CATEGORY))
export const decodeStoreStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(STORE_STATUS))
export const decodeReviewStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(REVIEW_STATUS))
export const decodeAppealStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(APPEAL_STATUS))
export const decodeAppealRole = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(APPEAL_ROLE))
export const decodeApplicationStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(APPLICATION_STATUS))
export const decodeAvailability = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(RIDER_AVAILABILITY))
export const decodeTicketKind = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(TICKET_KIND))
export const decodeTicketStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(TICKET_STATUS))
export const decodeOrderStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(ORDER_STATUS))
export const decodeAfterSalesRequestType = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(AFTER_SALES_REQUEST_TYPE))
export const decodeAfterSalesResolutionMode = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(AFTER_SALES_RESOLUTION_MODE))
export const decodePartialRefundStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(PARTIAL_REFUND_STATUS))
export const decodeEligibilityReviewTarget = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(ELIGIBILITY_REVIEW_TARGET))
export const decodePayoutAccountType = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(PAYOUT_ACCOUNT_TYPE))
export const decodeNoteStatus = (value: unknown, path = '$') => decodeEnum(value, path, Object.values(NOTE_STATUS))
