import {
  CURRENCY_CENTS_SCALE,
  MEMBER_AUTO_DISPATCH_MINUTES,
  STANDARD_AUTO_DISPATCH_MINUTES,
} from '@/shared/delivery/DeliveryServices'

export const CUSTOMER_PROFILE_COPY = {
  addressAddButton: '添加地址',
  addressCountLabel: '地址数量',
  addressManageButton: '地址管理',
  addressBookTicketKind: '地址簿',
  addressDeleteButton: '删除地址',
  addressDescription: '把常用地址维护独立出来，个人信息页只保留摘要。',
  addressLabelField: '地址标签',
  addressNewField: '新增地址',
  addressPageTitle: '地址管理',
  addressSavedBadge: '已保存',
  addressSetDefaultButton: '设为默认',
  addressDefaultDeleteHint: '如需删除当前默认地址，请先把其他地址设为默认。',
  balanceLabel: '账户余额',
  couponCountLabel: '优惠券数量',
  couponButton: '优惠券',
  couponDescription: '在个人信息内查看可用优惠券与使用门槛。',
  couponEmptyState: '当前没有可用优惠券。',
  couponMinSpendPrefix: '满 ',
  couponUsableSuffix: ' 可用',
  couponExpiresPrefix: '到期 ',
  couponPageTitle: '我的优惠券',
  couponTicketKind: '优惠券',
  currentAccountLabel: '当前账号',
  currentBalanceLabel: '当前余额',
  customAmountLabel: '自定义金额',
  customAmountPlaceholder: '输入充值金额，例如 88.8',
  defaultBadge: '默认',
  defaultAddressLabel: '默认地址',
  membershipLabel: '会员等级',
  membershipMember: '会员',
  membershipStandard: '普通',
  overviewAddressesButton: '管理地址',
  overviewCouponsButton: '优惠券',
  overviewDescription: '查看个人资料、会员状态、优惠券、地址簿和退款记录。',
  overviewRefundsButton: '退款记录',
  overviewTitle: '顾客信息',
  phoneLabel: '手机号',
  quickAmountsLabel: '快捷金额',
  rechargeConfirmButton: '确认充值',
  rechargeConfirmPreview: '本次将充值',
  rechargeDescription: '选择快捷金额或输入自定义金额，充值成功后将返回顾客信息页。',
  rechargeEstimatedBalanceSuffix: '，充值后余额预计为',
  rechargePresetAmountSuffix: ' 元',
  rechargeSelectIdlePrefix: '选择',
  rechargeSelectSelectedPrefix: '已选',
  rechargeTitle: '账户充值',
  rechargeActionButton: '充值',
  refundApprovedLabel: '已退款',
  refundCountLabel: '退款申请',
  refundDescription: '单独查看账号下全部退款申请和处理结果。',
  refundEmptyState: '当前还没有退款记录。',
  refundOrderTicketKind: '订单退款',
  refundOrderPrefix: '订单 #',
  refundApplyQuantityPrefix: '申请 ',
  refundApplyQuantitySuffix: ' 份',
  refundPendingLabel: '处理中',
  refundRejectedLabel: '已拒绝',
  refundPageTitle: '退款记录',
  refundResolutionNotePrefix: '处理说明：',
  refundReviewedAtPrefix: ' · 处理时间 ',
  refundSubmittedAtPrefix: '提交时间 ',
  refundTotalCountLabel: '退款总数',
  refundProcessingCountLabel: '处理中',
  refundApprovedCountLabel: '已退款',
  refundListButton: '查看退款',
  returnToProfileButton: '返回个人信息',
  spendLast30DaysLabel: '近 30 天消费',
  autoDispatchLabel: '自动派单时限',
  anonymousIdLabel: '匿名编号',
  noneDisplay: '--',
  previewSentenceSuffix: '。',
  rechargePreviewMarginTop: '16px',
  sectionSpacing: '20px',
} as const

export const CUSTOMER_PROFILE_RULES = {
  centsScale: CURRENCY_CENTS_SCALE,
  memberAutoDispatchMinutes: MEMBER_AUTO_DISPATCH_MINUTES,
  standardAutoDispatchMinutes: STANDARD_AUTO_DISPATCH_MINUTES,
} as const
