export const ORDER_PAGE_COPY = {
  workspace: {
    reviewPanelTitle: '订单评价',
    reviewPanelDescription: (maxRating: number, reviewWindowDays: number) =>
      `商家与骑手评价现在分开提交。${maxRating} 星可直接提交，非 ${maxRating} 星必须填写理由；评价入口仅保留到订单完成后 ${reviewWindowDays} 天内。`,
    orderPanelTitle: '顾客下单',
    selectedStoreTitle: (storeName: string) => `${storeName} · 店内点餐`,
    selectedStoreDescription: '当前已进入店铺，可先选好菜品，再前往购物车填写配送信息并支付。',
    selectedCategoryDescription: (categoryName: string) => `当前分类为「${categoryName}」，请选择对应餐厅。`,
    orderPanelDescription: '先选择细分餐厅大类，再进入对应餐厅选购菜品。',
  },
  review: {
    waitingRiderFallback: '待分配骑手',
    lowRatingReasonPlaceholder: (maxRating: number) => `非 ${maxRating} 星时必须填写理由`,
    sectionActionHint: (maxRating: number, minRating: number, lowRatingMax: number) =>
      `${maxRating} 星可直接提交，${minRating} 到 ${lowRatingMax} 星必须填写理由。`,
    storeButtonIdleLabel: '商家已评价',
    storeButtonReadyLabel: '提交商家评价',
    storeEmptyHint: '可以点击下方预设理由快速填写。',
    storeExtraNotePlaceholder: '商家补充说明（可选）',
    submittedRatingSubtitle: (rating: number) => `已提交 ${rating} 星`,
    pendingSubtitle: '待提交',
    storeTitle: '商家评价',
    riderActionHint: '你不需要和商家评价一起提交，可以分开完成。',
    riderButtonIdleLabel: '骑手已评价',
    riderButtonReadyLabel: '提交骑手评价',
    riderEmptyHint: '可以先选预设理由，再补充自己的描述。',
    riderExtraNotePlaceholder: '骑手补充说明（可选）',
    riderTitle: '骑手评价',
    backToOrdersButton: '返回订单',
    reviewWindowHint: (reviewWindowDays: number) =>
      `评价入口仅保留到订单完成后 ${reviewWindowDays} 天内。`,
  },
  partialRefund: {
    refundableQuantityLabel: (itemName: string, quantity: number) => `${itemName} 可退 ${quantity} 份`,
    reasonPlaceholder: '例如：这个菜没货就退掉',
    pendingButtonLabel: '退款申请处理中',
    submitButtonLabel: '申请退这件商品',
  },
  footer: {
    reviewActionHint: (remainingDays: number) =>
      `该订单仍在评价时限内，还剩 ${remainingDays} 天可评价商家和骑手。`,
    reviewActionButton: '去评价',
  },
  afterSales: {
    returnRequestOption: '退货申请',
    compensationRequestOption: '赔偿申请',
    compensationAmountPlaceholder: '期望赔偿金额（元）',
    returnReasonPlaceholder: '请描述退货原因，例如商品破损、严重变质',
    compensationReasonPlaceholder: '请描述赔偿原因，例如漏送、错送、超时严重',
    existingTicketButton: '已有售后处理中',
    submitButton: '提交售后申请',
  },
  display: {
    noAfterSalesSummary: '当前还没有售后申请，可提交退货或赔偿诉求。',
    afterSalesPendingPrefix: '售后申请处理中：',
    afterSalesApprovedLabel: '已通过',
    afterSalesRejectedLabel: '已驳回',
    afterSalesResolvedSummary: (approvedLabel: string, summary: string) => `售后${approvedLabel}：${summary}`,
    issuedCouponPrefix: ' · 已补发优惠券 ',
    compensationPrefix: ' · 处理金额 ',
    lineItemQuantitySeparator: ' x ',
    lineItemSelectionSeparator: ' · ',
    selectionGroupSeparator: '；',
    selectionOptionSeparator: '/',
    selectionValueSeparator: '：',
    refundedQuantityPrefix: ' · 已退 ',
    timelineNoteSeparator: ' · ',
    partialRefundHistoryLabel: '缺货退款',
    partialRefundPendingLabel: ' 待商家处理',
    partialRefundApprovedLabel: ' 已同意',
    partialRefundRejectedLabel: ' 已拒绝',
    reviewRevokedPrefix: '评价已撤销',
    reviewRevokedReasonSeparator: '：',
    storeReviewCommentPrefix: '商家理由：',
    storeReviewExtraNotePrefix: '商家补充：',
    riderReviewCommentPrefix: '骑手理由：',
    riderReviewExtraNotePrefix: '骑手补充：',
    merchantRejectReasonPrefix: '拒单理由：',
    currentCustomerFallback: '顾客',
    chatDisabledReason: '骑手尚未接单，当前聊天将先发送给商家；骑手接单后也能看到历史消息。',
  },
  chat: {
    roleCustomer: '顾客',
    roleMerchant: '商家',
    roleRider: '骑手',
    roleAdmin: '管理员',
    ticketKind: '订单沟通',
    title: '顾客 / 商家 / 骑手群聊',
    badgeSeparator: ' · ',
    emptyHint: '当前还没有沟通消息，可以先说明出餐、取餐或送达要求。',
    inputPlaceholder: '输入消息，例如请放门口、餐已备好、我已到店门口',
    submitButton: '发送',
  },
} as const
