import type { CustomerPropsArgs, PageState, PageView, SessionService } from './types'
import { getSharedFormattingProps } from './shared'

function getCustomerViewProps(pageView: PageView, navigate: CustomerPropsArgs['navigate']) {
  return {
    activeReviewOrder: pageView.activeReviewOrder,
    activeCustomerOrder: pageView.activeCustomerOrder,
    canReviewOrder: pageView.canReviewOrder,
    cartSubtotal: pageView.cartSubtotal,
    cartTotal: pageView.cartTotal,
    availableCheckoutCoupons: pageView.availableCheckoutCoupons,
    categoryStores: pageView.categoryStores,
    couponDiscountCents: pageView.couponDiscountCents,
    chooseStoreCategory: pageView.chooseStoreCategory,
    completedCustomerOrders: pageView.completedCustomerOrders,
    customerOrders: pageView.customerOrders,
    customerWorkspaceView: pageView.customerWorkspaceView,
    DELIVERY_FEE_CENTS: pageView.DELIVERY_FEE_CENTS,
    enterStore: pageView.enterStore,
    getRemainingReviewDays: pageView.getRemainingReviewDays,
    hasPendingRiderReview: pageView.hasPendingRiderReview,
    hasPendingStoreReview: pageView.hasPendingStoreReview,
    isStoreCurrentlyOpen: pageView.isStoreCurrentlyOpen,
    leaveStore: pageView.leaveStore,
    navigate,
    openCheckout: pageView.openCheckout,
    payableTotalCents: pageView.payableTotalCents,
    parsedRechargeAmount: pageView.parsedRechargeAmount,
    pendingCustomerReviewOrders: pageView.pendingCustomerReviewOrders,
    rechargeAmountError: pageView.rechargeAmountError,
    rechargeAmountPreview: pageView.rechargeAmountPreview,
    RECHARGE_PRESET_AMOUNTS: pageView.RECHARGE_PRESET_AMOUNTS,
    remainingBalanceAfterCheckout: pageView.remainingBalanceAfterCheckout,
    resetStoreCategory: pageView.resetStoreCategory,
    REVIEW_WINDOW_DAYS: pageView.REVIEW_WINDOW_DAYS,
    RIDER_REVIEW_REASON_OPTIONS: pageView.RIDER_REVIEW_REASON_OPTIONS,
    selectedCustomer: pageView.selectedCustomer,
    selectedCoupon: pageView.selectedCoupon,
    selectedStore: pageView.selectedStore,
    selectedStoreCanOrder: pageView.selectedStoreCanOrder,
    selectedStoreHasMenu: pageView.selectedStoreHasMenu,
    statusLabels: pageView.statusLabels,
    storeCustomerReviews: pageView.storeCustomerReviews,
    STORE_REVIEW_REASON_OPTIONS: pageView.STORE_REVIEW_REASON_OPTIONS,
    storeCategories: pageView.storeCategories,
    suggestedDeliveryTime: pageView.todayDeliveryWindow.minimumValue,
    todayDeliveryCutoff: pageView.todayDeliveryWindow.cutoffValue,
    updateQuantity: pageView.updateQuantity,
    updateReviewDraft: pageView.updateReviewDraft,
    visibleStores: pageView.visibleStores,
    ...getSharedFormattingProps(pageView),
  }
}

function getCustomerStateProps(pageState: PageState, sessionService: SessionService) {
  return {
    afterSalesDrafts: pageState.afterSalesDrafts,
    afterSalesErrors: pageState.afterSalesErrors,
    addressDraft: pageState.addressDraft,
    addressFormErrors: pageState.addressFormErrors,
    customerStoreSearch: pageState.customerStoreSearch,
    customerStoreSearchDraft: pageState.customerStoreSearchDraft,
    customerStoreSearchHistory: sessionService.customerStoreSearchHistory,
    customRechargeAmount: pageState.customRechargeAmount,
    customerNameDraft: pageState.customerNameDraft,
    deliveryAddress: pageState.deliveryAddress,
    deliveryAddressError: pageState.deliveryAddressError,
    isCheckoutExpanded: pageState.isCheckoutExpanded,
    orderChatDrafts: pageState.orderChatDrafts,
    orderChatErrors: pageState.orderChatErrors,
    partialRefundDrafts: pageState.partialRefundDrafts,
    partialRefundErrors: pageState.partialRefundErrors,
    quantities: pageState.quantities,
    remark: pageState.remark,
    scheduledDeliveryTime: pageState.scheduledDeliveryTime,
    reviewDrafts: pageState.reviewDrafts,
    reviewErrors: pageState.reviewErrors,
    selectedCouponId: pageState.selectedCouponId,
    selectedRechargeAmount: pageState.selectedRechargeAmount,
    scheduledDeliveryError: pageState.scheduledDeliveryError,
    selectedStoreCategory: pageState.selectedStoreCategory,
    setAddressDraft: pageState.setAddressDraft,
    setAddressFormErrors: pageState.setAddressFormErrors,
    setAfterSalesDrafts: pageState.setAfterSalesDrafts,
    setAfterSalesErrors: pageState.setAfterSalesErrors,
    setCustomRechargeAmount: pageState.setCustomRechargeAmount,
    setCustomerNameDraft: pageState.setCustomerNameDraft,
    setCustomerStoreSearch: pageState.setCustomerStoreSearch,
    setCustomerStoreSearchDraft: pageState.setCustomerStoreSearchDraft,
    setDeliveryAddress: pageState.setDeliveryAddress,
    setDeliveryAddressError: pageState.setDeliveryAddressError,
    setError: sessionService.setError,
    setIsCheckoutExpanded: pageState.setIsCheckoutExpanded,
    setOrderChatDrafts: pageState.setOrderChatDrafts,
    setOrderChatErrors: pageState.setOrderChatErrors,
    setPartialRefundDrafts: pageState.setPartialRefundDrafts,
    setPartialRefundErrors: pageState.setPartialRefundErrors,
    setRemark: pageState.setRemark,
    setReviewDrafts: pageState.setReviewDrafts,
    setReviewErrors: pageState.setReviewErrors,
    setScheduledDeliveryError: pageState.setScheduledDeliveryError,
    setScheduledDeliveryTime: pageState.setScheduledDeliveryTime,
    setScheduledDeliveryTouched: pageState.setScheduledDeliveryTouched,
    setSelectedCouponId: pageState.setSelectedCouponId,
    setSelectedRechargeAmount: pageState.setSelectedRechargeAmount,
    stateTickets: sessionService.state?.tickets ?? [],
  }
}

export function buildCustomerProps({
  pageView,
  pageState,
  sessionService,
  navigate,
  addCustomerAddress,
  getRemainingRefundableQuantity,
  openRechargePage,
  removeCustomerAddress,
  setDefaultCustomerAddress,
  saveCustomerName,
  selectRechargeAmount,
  clearCustomerStoreSearchHistory,
  removeCustomerStoreSearchHistoryItem,
  submitAfterSalesRequest,
  submitCustomerStoreSearch,
  submitOrder,
  submitOrderChatMessage,
  submitPartialRefundRequest,
  submitRechargeFromPage,
  submitReview,
  canSubmitPartialRefund,
}: CustomerPropsArgs) {
  return {
    ...getCustomerViewProps(pageView, navigate),
    ...getCustomerStateProps(pageState, sessionService),
    addCustomerAddress,
    getRemainingRefundableQuantity,
    openRechargePage,
    removeCustomerAddress,
    setDefaultCustomerAddress,
    saveCustomerName,
    selectRechargeAmount,
    clearCustomerStoreSearchHistory,
    removeCustomerStoreSearchHistoryItem,
    submitAfterSalesRequest,
    submitCustomerStoreSearch,
    submitOrder,
    submitOrderChatMessage,
    submitPartialRefundRequest,
    submitRechargeFromPage,
    submitReview,
    canSubmitPartialRefund,
  }
}
