import type { CustomerRoleProps } from '@/pages/DeliveryConsole/functions/roleProps'

export type CheckoutPanelProps = Pick<
  CustomerRoleProps,
  | 'availableCheckoutCoupons'
  | 'cartSubtotal'
  | 'couponDiscountCents'
  | 'customerRequiresDefaultAddressUpdate'
  | 'deliveryFeeCents'
  | 'deliveryAddress'
  | 'deliveryAddressError'
  | 'formatPrice'
  | 'isCheckoutExpanded'
  | 'monthlySalesByMenuItem'
  | 'menuItemConfigurationModal'
  | 'openCheckout'
  | 'openMenuItemConfiguration'
  | 'openRechargePage'
  | 'payableTotalCents'
  | 'quantities'
  | 'remainingBalanceAfterCheckout'
  | 'remark'
  | 'scheduledDeliveryError'
  | 'scheduledDeliveryTime'
  | 'selectedCoupon'
  | 'selectedCouponId'
  | 'selectedCustomer'
  | 'selectedMenuItemConfigurations'
  | 'selectedStore'
  | 'selectedStoreCanOrder'
  | 'selectedStoreHasMenu'
  | 'closeMenuItemConfiguration'
  | 'confirmMenuItemConfiguration'
  | 'setDeliveryAddress'
  | 'setDeliveryAddressError'
  | 'setError'
  | 'setIsCheckoutExpanded'
  | 'setRemark'
  | 'setScheduledDeliveryError'
  | 'setScheduledDeliveryTime'
  | 'setScheduledDeliveryTouched'
  | 'setSelectedCouponId'
  | 'submitOrder'
  | 'suggestedDeliveryTime'
  | 'todayDeliveryCutoff'
  | 'updateCartLineQuantity'
  | 'updateQuantity'
  | 'isStoreCurrentlyOpen'
  | 'selectedStoreDeliveryDistanceLabel'
  | 'selectedStoreDistanceCategory'
  | 'selectedStoreIsDeliverable'
> & {
  deliveryAddressIsLocated?: boolean
  deliveryAddressIsLocating?: boolean
}
